version: '3.1'
name: promut
services:
    mutnmt:
        container_name: mutnmt
        image: mutnmt:latest
        build: .
        ports:
            - "8095:5000"
        environment: 
            DEBUG: 1
            CREDENTIALS_USERNAME: admin
            CREDENTIALS_PASSWORD: admin
            SHELL: /bin/bash
        volumes:
            - ./data:/opt/mutnmt/data
            - ./app/preloaded:/opt/mutnmt/app/preloaded
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: ['0']
                          capabilities: [gpu, utility, compute]

networks:
  default:
    name: mutnmt_tudor