version: '3.1'

services:
    mutnmt_demo:
        container_name: mutnmt_demo
        image: mutnmt_demo:latest
        build: .
        ports:
            - "8090:5010"
        environment: 
            DEBUG: 1
            CREDENTIALS_USERNAME: admin
            CREDENTIALS_PASSWORD: admin
            SHELL: /bin/bash
        volumes:
            - ./data:/opt/mutnmt/data
            - ./app/preloaded:/opt/mutnmt/app/preloaded
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu, utility, compute]

networks:
  default:
    name: mutnmt_demo