version: '3.1'

services:
    mutnmt_tudor:
        container_name: mutnmt_tudor
        image: mutnmt_tudor:latest
        build: .
        ports:
            - "8087:5007"
        environment: 
            DEBUG: 1
            CREDENTIALS_USERNAME: admin
            CREDENTIALS_PASSWORD: admin
            SHELL: /bin/bash
        volumes:
            - ./data:/opt/mutnmt/data
            - ./app/preloaded:/opt/mutnmt/app/preloaded
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: ['0']
                          capabilities: [gpu, utility, compute]

networks:
  default:
    name: mutnmt_tudor