version: '3.1'

services:
    mutnmt_lukas:
        container_name: mutnmt_lukas
        image: mutnmt_lukas:latest
        build: .
        ports:
            - "8091:5011"
        environment: 
            DEBUG: 1
            CREDENTIALS_USERNAME: admin
            CREDENTIALS_PASSWORD: admin
            SHELL: /bin/bash
        volumes:
            - ./data:/opt/mutnmt/data
            - ./app/preloaded:/opt/mutnmt/app/preloaded
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: ['1']
                          capabilities: [gpu, utility, compute]